version: '3.8'

services:
  api:
    image: virtuscorp_backend:latest
    ports:
      - "8000:8000"
    depends_on:
      - db
    secrets:
      - db_password
    environment:
      - DATABASE_URL=postgresql://postgres:@db:5432/virtuscorp_db

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: virtuscorp_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    secrets:
      - db_password

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@virtuscorp.local
      PGADMIN_DEFAULT_PASSWORD: supersecure
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin_data:

secrets:
  db_password:
    external: true
